executor: KubernetesExecutor
dags:
  gitSync:
    enabled: true
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO.git
    branch: main
    subPath: dags
    syncInterval: 60
    credentialsSecret: git-creds
config:
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
  AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: "s3_conn"
  AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: "s3://airflow-logs/"
  AIRFLOW__CORE__REMOTE_LOGGING: "True"
logs:
  persistence:
    enabled: false
webserver:
  service:
    type: NodePort
    nodePort: 30080
env:
  - name: AWS_ACCESS_KEY_ID
    value: minioadmin
  - name: AWS_SECRET_ACCESS_KEY
    value: minioadmin
  - name: AIRFLOW__KUBERNETES__DELETE_WORKER_PODS
    value: "True"
  - name: AIRFLOW__KUBERNETES__NAMESPACE
    value: "default"
