apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: scala-spark-job
spec:
  type: Scala
  mode: cluster
  image: nickpeachey/sparkminiosaver:0.0.4
  imagePullPolicy: Always
  mainClass: com.cawooka.MainExecutor
  mainApplicationFile: "local:///opt/spark/app/spark-minio-saver.jar"
  sparkVersion: "3.5.5"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: 512m
    serviceAccount: spark
    labels:
      version: 3.5.5
  executor:
    cores: 1
    instances: 2
    memory: 512m
    labels:
      version: 3.5.5
  sparkConf:
    "spark.eventLog.enabled": "true"
    "spark.eventLog.dir": "s3a://spark-events"
    "spark.hadoop.fs.s3a.endpoint": "http://minio.minio.svc.cluster.local:9000"
    "spark.hadoop.fs.s3a.access.key": "eF8UaaYZ9xhPJha6scs8"
    "spark.hadoop.fs.s3a.secret.key": "fVW9DFwL3V05pDXnsjeVk3S7NANKFrxf"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
