apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: scala-spark-job-debug
spec:
  type: Scala
  mode: cluster
  image: nickpeachey/sparkminiosaver:3.0.19
  imagePullPolicy: Always
  mainClass: "com.cawooka.MainExecutor"
  mainApplicationFile: "local:///opt/spark/jars/spark-debug-app.jar"

  sparkVersion: "3.5.5"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: 512m
    serviceAccount: spark
    labels:
      version: 3.5.5
  executor:
    cores: 1
    instances: 1
    memory: 512m
    labels:
      version: 3.5.5
